#!/bin/bash

# inspired by junegunn's dotfiles

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
mkdir ~/.config/nvim
mv -v ~/.config/nvim/init.vim ~/.config/nvim/init.vim.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc
ln -sf $BASE/init.vim ~/.config/nvim/init.vim

vim +PlugInstall +qall
nvim +PlugInstall +qall
