#!/bin/bash

# inspired by junegunn's dotfiles

# RC files
cd $(dirname $BASH_SOURCE)
BASE=$(pwd)
for rc in *rc gitmessage gitconfig gitignore agignore tmux.conf; do
  mkdir -pv bak
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

curl -fLo ~/z/z.sh --create-dirs https://raw.githubusercontent.com/rupa/z/master/z.sh

sh install-vim
